### ISSUE TITLE
`__init__` hangs forever on bad connection

### ISSUE THREAD

**Issue by rmaronson** [ddetommaso/TobiiGlassesPyController#14]
The `while` loop in `wait_for_status` should take a timeout and return or throw an exception after the sleep counter reaches that value, and `__init__` should take a timeout param that it passes to `__connect__`. Otherwise I have to force-kill it every time I mistype the ip!

**Comment by ddetommaso** [comment]
Adding a timeout it's definitely a nice improvement! 
Please feel free to open PR!

Any further help is much appreciated!Thanks

**Comment by rmaronson** [comment]
added #15
