### ISSUE TITLE
The calibration of tobii 

### ISSUE THREAD

**Issue by yuanyuanqiao0919** [ddetommaso/TobiiGlassesPyController#19]
hello, Sir.I am writing to ask you some questions about the project TobiiGlassesPyController you posted on github.We cannot successfully complete the calibration of tobii with  the 
 example live_scene_and_gaze.py, program clocked and no return value as shown in the following figure. Is there anything we should pay attention to?Looking forward to your reply.Thank you very much.

![image](https://user-images.githubusercontent.com/37893827/84625913-bfc93f80-af16-11ea-8c38-fe128b72597a.png)

**Comment by ddetommaso** [comment]
Hi @yuanyuanqiao0919 

from the debug output everything's seems fine.
Please try to run the scripts connect.py and calibrate_and_record.py scripts and report here the outputs.
Thanks

**Comment by yuanyuanqiao0919** [comment]
Thank you for your reply,i will have a try!

**Comment by yuanyuanqiao0919** [comment]
Cleared the SD card and everything worked fine. Thank you for your patience！
