### ISSUE TITLE
TobiiGlassesController and Labstreaming Layer Example 

### ISSUE THREAD

**Issue by jabarragann** [ddetommaso/TobiiGlassesPyController#20]
Hi first of all thanks for doing this really great job. I took your streaming example and adapted it to stream the data from the controller to Labstreaminglayer (LSL). Really useful in case you want to record more signals along with the eye tracker.

 If this is interesting I could send a pull request so that you have that additional example in your repository

**Comment by ddetommaso** [comment]
Hi @jabarragann 

having an example working with LSL would be really great!!
Please I'd ask you to proceed with the PR.

Thank you for your work!
