### ISSUE TITLE
live_scene Execution error

### ISSUE THREAD

**Issue by SeungYoonLee1** [ddetommaso/TobiiGlassesPyController#21]
Hello, I am a college student living in Korea.
First of all, I have Tobii Glass 2. I downloaded the GitHub source code you uploaded and ran live_scene.py, but there was an error, so I'd like to ask you.

I connected the eye tracker to the laptop using Ethernet connection, and I modified IPv6 of the existing code.
If you know what's wrong with running live_scene.py, please answer! Thank you.

Is there any requirement for running live_scene.py?

**Comment by ddetommaso** [comment]
Hi @SeungYoonLee1 

could you please report here the error ?

**Comment by SeungYoonLee1** [comment]
First of all, I connected the eye tracker to my laptop through an Ethernet connection.

1. Check Ethernet

![IPv6 Ethernet](https://user-images.githubusercontent.com/69844293/108463931-9db46800-72c2-11eb-88e1-2bf645eafbde.JPG)

2. Modify live_scene.py

![live_scene Code](https://user-images.githubusercontent.com/69844293/108463950-a4db7600-72c2-11eb-8ccf-8b80decd8951.JPG)

3. When running python live_scene.py, the following error occurred. If you know the solution, I'd appreciate it if you could teach me!

![error](https://user-images.githubusercontent.com/69844293/108464330-42cf4080-72c3-11eb-85b1-9a7b511ccabf.JPG)

**Comment by SeungYoonLee1** [comment]
First of all, I connected the eye tracker to my laptop through an Ethernet
connection.

   1. Check Ethernet

[image: IPv6 Ethernet]
<https://user-images.githubusercontent.com/69844293/108463931-9db46800-72c2-11eb-88e1-2bf645eafbde.JPG>

   1. Modify live_scene.py

[image: live_scene Code]
<https://user-images.githubusercontent.com/69844293/108463950-a4db7600-72c2-11eb-8ccf-8b80decd8951.JPG>

   1. When running python live_scene.py, the following error occurred. If
   you know the solution, I'd appreciate it if you could teach me!

[image: error]
<https://user-images.githubusercontent.com/69844293/108464330-42cf4080-72c3-11eb-85b1-9a7b511ccabf.JPG>

2021년 2월 19일 (금) 오전 12:00, Davide De Tommaso <notifications@github.com>님이
작성:

**Comment by ddetommaso** [comment]
Hi @SeungYoonLee1 ,

we have already addressed this kind of issue in #3 
Please have a look and see if you can solve it!

**Comment by SeungYoonLee1** [comment]
I've already checked the #issue3 you sent me, but there were only contents
related to IPv4.
Unfortunately, I couldn't run it with IPv4 because the Tobii classes2 I
have is a model that doesn't support Wi-Fi.
Is there any way to run live_scene.py with IPv6 over an Ethernet connection?

2021년 2월 19일 (금) 오후 5:42, Davide De Tommaso <notifications@github.com>님이 작성:

**Comment by ddetommaso** [comment]
Hi @SeungYoonLee1 ,

you can still use IPv4 with Ethernet connection.
Please check out [https://github.com/ddetommaso/TobiiGlassesPyController/wiki/2.-Network-connection](url)
