### ISSUE TITLE
How to Install - 2 errors

### ISSUE THREAD

**Issue by Nicolasr3** [ddetommaso/TobiiGlassesPyController#23]
When I was trying to install the TobiiGlassesPyController in python 3.8.5 I got the following errors:
1. ERROR: Failed building wheel for netifaces
2. ERROR: Command errored out with exit status 1: /home/nrussi/git-local/tobii-glasses/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-blj7nhdx/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-blj7nhdx/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uavo0mcu/install-record.txt --single-version-externally-managed --compile --install-headers /home/nrussi/git-local/tobii-glasses/venv/include/site/python3.8/netifaces Check the logs for full command output.

In python 3.6 there was no problem.

**Comment by ddetommaso** [comment]
Fixed
