### ISSUE TITLE
'calibrate_and_record.py' Data storage format

### ISSUE THREAD

**Issue by SeungYoonLee1** [ddetommaso/TobiiGlassesPyController#26]
Hello, I don't know if you remember, but I am a university student living in Korea who studied and inquired about how to utilize data using Tobii in ROS.

Thanks to your kind reply last time, I was able to proceed smoothly with sending and receiving data from ROS.

I'm asking you again because I have a question.

If you run the code 'calibrate_and_record.py', you can see that the data is saved in the form of a json file.

I would like to save this data as a csv file to utilize it smoothly.

So I'm looking at the 'tobiiglassesctrl' module to modify the way data is stored, and I don't know how to approach it.

If you know how, could you give me some advice or hints?

Thank you so much!

**Comment by ddetommaso** [comment]
Hi @SeungYoonLee1 

happy to hear that you integrated successfully the controller in ROS!
About the exporting in csv is a feature already implemented in the TobiiGlassesPySuite.

Please have a look in the paper https://dl.acm.org/doi/abs/10.1145/3314111.3319828 and the examples in the public repo and you'll find the answer and many other examples.

Best!

**Comment by SeungYoonLee1** [comment]
Hello! As you replied, we downloaded 'PySuite' from github and looked at
the files to find out how to save Tobii data in csv format.

I looked at the Python files in the tobiiglasses module and looked at the
functions saved in csv format. I have a question.

First of all, I found a pdf file in the pysuit while I was looking for how
to load and use these functions (I attached this file).

There's something in this file that looks like an example code that you
save in csv format, so I tried to do it this way, and there was an error.
Perhaps there is a problem with the parameter that I handed over to the
function, but I am not sure what to put in the parameter value. (This
example code photo is attached.)

Could you give me any hint or example code for saving tobii data in csv
format?

Thank you for always responding kindly.
Thanks to the files you uploaded on github, it was very helpful to proceed
with the research.

Thank you!

2021년 7월 16일 (금) 오후 5:54, Davide De Tommaso ***@***.***>님이 작성:

**Comment by SeungYoonLee1** [comment]
2021년 7월 21일 (수) 오후 5:56, 이승윤 ***@***.***>님이 작성:

**Comment by ddetommaso** [comment]
Hi @SeungYoonLee1 

please check out [this example ](https://github.com/ddetommaso/TobiiGlassesPySuite-Examples/blob/624e0067428479a7f958d9842d7d16386f2ae429/export/export_rawdata.py) for saving raw data in a csv file.

As parameters you need to provide:
- projects_dir (The path of the directory where projects.ttgp is located, very likely your SD card path)
- project_id (The project_id (or folder name) from where importing the recordings)
- recording_id (The recording_id (or folder name) from where import the segments)

You can get those information using [these scripts](https://github.com/ddetommaso/TobiiGlassesPySuite-Examples/tree/624e0067428479a7f958d9842d7d16386f2ae429/info)

**Comment by SeungYoonLee1** [comment]
Thank you very much!

2021년 7월 21일 (수) 오후 10:57, Davide De Tommaso ***@***.***>님이
작성:
