### ISSUE TITLE
I have 'time stamp error' in Pysuite CSV

### ISSUE THREAD

**Issue by de1403** [ddetommaso/TobiiGlassesPyController#28]
Hi ! 

I made a recording video project using tobii glasses, and created a csv file using Pysuite.
However, the time stamp in the csv file gives an error. If I change the time stamp to an absolute time, it returns to the 1970s.
Could you tell me how to fix this part?

![캡처](https://user-images.githubusercontent.com/55389509/130945341-84699e93-3493-4b46-9fc8-c4378fcefe2c.PNG)

And I have one more question.
When playing tobii live, is there a way to save 'project' to the SD card like when recording tobii? 'Project' is the folder with livedata.json or videos that will be played live.

**Comment by ddetommaso** [comment]
Hi @de1403 

please report all issues regarding the issue in the proper repository 

https://github.com/ddetommaso/TobiiGlassesPySuite

Thanks
