### ISSUE TITLE
Convert python code to c++ code

### ISSUE THREAD

**Issue by 962557346** [ddetommaso/TobiiGlassesPyController#9]
Hello, the python code can be converted  to c++ code easily? C++ code is more convenient because of my needs.

**Comment by ddetommaso** [comment]
Hi there,

TobiiGlassesPyController is an open-source project not supported by Tobii AB or any other sponsor. The code can be surely ported to C++ but it requires time and at the moment I haven't the resources to start a new project.

Thank you for your comment
